config: conf/tuning/train_asr_transformer5.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/asr_train_asr_transformer5_raw_kr_char
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: 2
dist_rank: 0
local_rank: 0
dist_master_addr: localhost
dist_master_port: 35309
dist_launcher: null
multiprocessing_distributed: true
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 100
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
grad_clip: 5.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: null
use_tensorboard: true
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: null
batch_size: 64
valid_batch_size: null
batch_bins: 1000000
valid_batch_bins: null
train_shape_file:
- exp/asr_stats_raw_kr_char/train/speech_shape
- exp/asr_stats_raw_kr_char/train/text_shape.char
valid_shape_file:
- exp/asr_stats_raw_kr_char/valid/speech_shape
- exp/asr_stats_raw_kr_char/valid/text_shape.char
batch_type: folded
valid_batch_type: null
fold_length:
- 80000
- 150
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/train_nodev/wav.scp
    - speech
    - sound
-   - dump/raw/train_nodev/text
    - text
    - text
valid_data_path_and_name_and_type:
-   - dump/raw/train_dev/wav.scp
    - speech
    - sound
-   - dump/raw/train_dev/text
    - text
    - text
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000
token_list:
- <blank>
- <unk>
- <space>
- ㄴ
- ㅏ
- ㅇ
- ㅣ
- ㄱ
- ㄹ
- ㅓ
- ㅡ
- ㅁ
- ㅗ
- ㄷ
- ㅈ
- ㅅ
- ㅔ
- ㅎ
- ㅜ
- ㅐ
- ㅂ
- ㅕ
- ㅆ
- ㅛ
- ㄲ
- ㅊ
- ㄸ
- ㅘ
- ㅌ
- ㅋ
- ㅑ
- ㅍ
- '?'
- ㅉ
- ㅚ
- ㅝ
- ㅢ
- ㅃ
- ㅖ
- ㅠ
- ㅟ
- ㅙ
- ㅒ
- ㅞ
- S
- T
- C
- B
- P
- M
- t
- I
- s
- N
- F
- D
- K
- A
- L
- b
- G
- m
- E
- V
- k
- O
- R
- p
- c
- e
- U
- n
- X
- i
- a
- f
- g
- ‘
- x
- u
- l
- o
- H
- ’
- '!'
- v
- r
- '>'
- <
- d
- W
- Q
- Y
- '"'
- J
- ㆍ
- '1'
- '`'
- y
- )
- ·
- h
- ''''
- Z
- w
- _
- “
- j
- q
- ㄼ
- ”
- ％
- z
- '~'
- ¥
- ♡
- <sos/eos>
init: xavier_uniform
input_size: null
ctc_conf:
    dropout_rate: 0.0
    ctc_type: builtin
    reduce: true
    ignore_nan_grad: true
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
use_preprocessor: true
token_type: char
bpemodel: null
non_linguistic_symbols: null
cleaner: null
g2p: null
speech_volume_normalize: null
rir_scp: null
rir_apply_prob: 1.0
noise_scp: null
noise_apply_prob: 1.0
noise_db_range: '13_15'
frontend: default
frontend_conf:
    fs: 16k
specaug: null
specaug_conf: {}
normalize: global_mvn
normalize_conf:
    stats_file: exp/asr_stats_raw/train/feats_stats_61.npz
preencoder: null
preencoder_conf: {}
encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true
postencoder: null
postencoder_conf: {}
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0
required:
- output_dir
- token_list
version: 0.10.2a1
distributed: true
